apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          volumeMounts:
            - mountPath: /ebs-mount
              name:  external-ebs
      volumes:
        - name: external-ebs
          persistentVolumeClaim:
            claimName: dynamic-external-ebs