apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: external-efs
spec:
  resources:
    requests:
      storage: 18G
  storageClassName: preprov-ebs
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  volumeName: efs-pv
