storage:
  storage-folder-path: ${STORAGE_FOLDER_PATH:/tmp}
  config-folder-path: ${CONFIG_FOLDER_PATH:/config}
  validate-config: ${VALIDATE_CONFIG:false}
service:
  url: ${SERVICE_URL:k8sshowcase}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

management:
  endpoint:
    health:
      enabled: true
    shutdown:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, prometheus, shutdown
      base-path: /
  server:
    port: 9090

