storage:
  folder-path: ${STORAGE_FOLDER_PATH:/tmp}
  validate-config: ${VALIDATE_CONFIG:false}

management:
  endpoint:
    health:
      enabled: true
    shutdown:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, prometheus, shutdown
      base-path: /
  server:
    port: 9090

