apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: k8sshowcase
    environment: test
  name: k8sshowcase
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8sshowcase
  template:
    metadata:
      labels:
        app: k8sshowcase
        environment: test
    spec:
      containers:
        - image: quay.io/datawire/ambassador:1.10.0
          name: k8s-showcase-application
          volumeMounts:
            - mountPath: /persistent-volume
              name: persistent-volume
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: k8sshowcase
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: failure-domain.beta.kubernetes.io/zone
              labelSelector:
               matchExpressions:
                - key: app
                  operator: In
                  values:
                    - k8sshowcase
