apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8sshowcase
  labels:
    app: k8sshowcase
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ionos-enterprise-hdd
  resources:
    requests:
      storage: 1Gi