apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8sshowcase-snapshot
  labels:
    app: k8sshowcase
spec:
  accessModes:
    - ReadWriteOnce
  dataSource:
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
    name: k8sshowcase
  resources:
    requests:
      storage: 1Gi