apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8sshowcase
  name: k8sshowcase
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: k8sshowcase
  sessionAffinity: None
  type: ClusterIP